### ISSUE TITLE
Parsing multiple trees

### ISSUE THREAD

**Issue by daviddao** [lczech/genesis#2]
It would be super awesome to be able to parse <b>multiple</b> newick strings in one txt file and also ignoring tree names

```
Example File: 

Tree_A:
((A:2,B:3):3,D);
Tree_B:
(E:4,(A:3,C:D):3);
```

**Comment by lczech** [comment]
Already started with it. 

Why is it important to ignore tree names? My approach would be to create something like a map from name to Tree object, so that users who need the names can use them, but the others just iterate over the values of the map.

**Comment by daviddao** [comment]
Agreed. A map would be a very elegant and also pythonic way in doing things. Forget ignoring tree names, your approach is much better!

**Comment by lczech** [comment]
TreeSet now has some basic methods to work with multiple trees:
- Add (named) trees
- Find tree by name
- Get tree by index
- Iterate over all trees

Furthermore, the Newick parser can deal with files containing multiple trees and can:
- Read a file with trees into a TreeSet
- Read multiple files (possibly with multiple trees each) into a TreeSet
- Both methods also available for parsing from a given string (which contains Newick trees) or multiple strings

It compiles, but is not (yet) tested well. Everything that does not work will be fixed as a bug in the future. Also, further methods might be added to TreeSet if needed.
