### ISSUE TITLE
make: *** [Makefile:84: all] Error 2

### ISSUE THREAD

**Issue by vinitamehlawat** [lczech/genesis#6]
Hi @frederic-mahe 

I  clone the repository for `genesis` and tried to install it but when I call `make`  in the main directory it is giving this error: 

**make[2]: *** [lib/genesis/CMakeFiles/genesis_lib_shared.dir/build.make:63: lib/genesis/CMakeFiles/genesis_lib_shared.dir/__/__/genesis_unity_sources/lib/all.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:144: lib/genesis/CMakeFiles/genesis_lib_shared.dir/all] Error 2
make: *** [Makefile:84: all] Error 2**

It would be very helpful if you could please suggest why this software is not installing 

Thank you 
Vinita

**Comment by lczech** [comment]
Hi @vinitamehlawat,

I've seen that you also opened a similar issue at [BenoitMorel/covid19_cme_analysis](https://github.com/BenoitMorel/covid19_cme_analysis/issues/1) - are these two connected?

So, from the error message that you posted above, I cannot tell much. Could you please post the full output of the make/cmake step here?

Thanks
Lucas

**Comment by vinitamehlawat** [comment]
Hi @lczech 

Yes I have also posted this same error to https://github.com/BenoitMorel/covid19_cme_analysis/issues/1 because I am having sars-cov2 data and for that data I want to create a robust phylogenetic tree and for this I am using there scripts but as you can see my genesis software is giving error so for that I raised issue for this software at both places.
I tried to call `make` in the `bin` as well as `build` directory.

Here I am attaching a screen-shot of the full error whic I got on my terminal:

![genesis_error](https://user-images.githubusercontent.com/47384975/138399581-e45273f6-ea8e-41f8-8907-7a1db1b23773.png)

**Comment by lczech** [comment]
Thanks, I see the issue now. Somehow, you ended up with a genesis version that is in between a change of a feature. How did you obtain the copy of genesis in your home directory `~/genesis`? Is that from the covid19_cme_analysis project, or did you clone or copy a version of genesis directly into there?

Also, @Pbdas, @BenoitMorel, does [covid19_cme_analysis](https://github.com/BenoitMorel/covid19_cme_analysis) specify a particular commit of genesis when downloading? If not, that might cause the issue here - not sure how, but it smells like it.

**Comment by vinitamehlawat** [comment]
For genesis I just install `setup.sh` of https://github.com/BenoitMorel/covid19_cme_analysis but on linux mint and mac this repo is not installing but when I tried on Ubuntu server this works and all softwares installed without any error massase but the bin/apps folder is also epmpty there. For standalone I clone `genesis` from http://doc.genesis-lib.org/setup.html link and realised that this genesis is not installed properly in my home directory as well.

**Comment by BenoitMorel** [comment]
Hi Vinita and Lucas,

we download the most recent version of genesis (which was not very wise :D):
``` 
  git clone --recursive https://github.com/lczech/genesis.git
```

@lczech can you tell me which commit we should target in the setup script? I can do the update.

Best,
Benoit

**Comment by lczech** [comment]
I was able to reproduce the exact issue that @vinitamehlawat  described above.

But I am not entirely sure which version of genesis I used back there. It compiles for me with this change in https://github.com/BenoitMorel/covid19_cme_analysis/blob/master/setup.sh

```
install_genesis() {
  git clone --recursive https://github.com/lczech/genesis.git
  cd genesis
  git checkout e71a89704a87634ea84c1d15e80bafac234e0824
  echo "Installing genesis..."
  cd apps
  ln -s ../../../scripts/*.cpp .
  cd ..
  make -j 8
  make update -j 8
  cd ..
}
```

Let me know if this works for you as well :-)

UPDATE: I'm currently travelling, and don't have access to my hard drive where I have the covid project files on. I'll check next week which genesis version we actually used back then - but until then, you can use the one above to get it work for now.

PS: I also found some other issues when compiling the current master branch of genesis, which I'll fix later. Thanks for reporting this :-)

**Comment by BenoitMorel** [comment]
I have updated the setup script in the covid project.
@vinitamehlawat  you can update it with the `git pull` command.

If you find any other error while installing the project, you can open an issue in our repository https://github.com/BenoitMorel/covid19_cme_analysis

**Comment by lczech** [comment]
Hi @vinitamehlawat,

I've fixed the error in the genesis master branch [that you described above](https://github.com/lczech/genesis/issues/6#issuecomment-949304194), thanks for that!

Also, as he wrote above, @BenoitMorel has updated the [covid19 project](https://github.com/BenoitMorel/covid19_cme_analysis), it seems that this is fixed now. Please let us know if that worked.

I'm going to close this issue now. Feel free to re-open it should you still have problems with genesis, and please feel free to post another issue in the covid19 repository should something there still not work out!

All the best
Lucas

**Comment by vinitamehlawat** [comment]
Hi @lczech  

Please accept my apologies for the delay in responding; I reinstalled the genesis and it worked properly for me without any errors.

Thank you
Vinita

**Comment by lczech** [comment]
Thank you, glad to hear!
